site_name: System Administrator Guide
repo_url: https://github.com/civicrm/civicrm-sysadmin-guide
site_description: A guide for CiviCRM system administrators.
site_author: The CiviCRM community
theme: material

pages:
- Home: index.md
- Planning your site:
  - Identifying your needs: planning/index.md
  - Trying a demo: planning/demo.md
  - Hosting: planning/hosting.md
  - Choosing a CMS: planning/cms.md
  - Transitioning to CiviCRM: planning/transition.md
- Requirements: requirements.md
- Installation:
  #- Install in Drupal 8: install/drupal8.md
  - Install in Drupal 7: install/drupal7.md
  - Install in WordPress: install/wordpress.md
  - Install in Joomla: install/joomla.md
  - Install in Backdrop: install/backdrop.md
  - Multi-site installation: install/multi-site.md
- Setup:
  - Setup: setup/index.md
  - Backups: setup/backups.md
  #- Monitoring: setup/monitoring.md
  - Securing your site: setup/security.md
  #- Data migration: setup/migration.md
  - Site key: setup/site-key.md
  - Scheduled jobs: setup/jobs.md
  - Directories: setup/directories.md
  - Caches: setup/cache.md
  - CiviMail setup:
    - CiviMail setup: setup/civimail/index.md
    - Outbound mail: setup/civimail/outbound.md
    - Inbound mail: setup/civimail/inbound.md
    - Deliverability: setup/civimail/deliverability.md
  - Payment processors:
    - Payment processors: setup/payment-processors/index.md
    - Recurring Payments: setup/payment-processors/recurring.md
    - Authorize.net: setup/payment-processors/authorize-net.md
    - Card Access: setup/payment-processors/card-access.md
    - First Data: setup/payment-processors/first-data.md
    - iATS: setup/payment-processors/iats.md
    - Moneris: setup/payment-processors/moneris.md
    - PayFlow: setup/payment-processors/payflow.md
    - PayJunction: setup/payment-processors/payjunction.md
    - PayPal Standard: setup/payment-processors/paypal-standard.md
    - PayPal Pro and Express: setup/payment-processors/paypal-pro.md
    - Ogone: setup/payment-processors/ogone.md
  - Detailed logging: setup/logging.md
  - Optimizations: setup/optimizations.md
- Upgrades:
  - Upgrades: upgrade/index.md
  #- Upgrade in Drupal 8: upgrade/drupal8.md
  - Upgrade in Drupal 7: upgrade/drupal7.md
  - Upgrade in WordPress: upgrade/wordpress.md
  - Upgrade in Joomla: upgrade/joomla.md
  - Upgrade in Backdrop: upgrade/backdrop.md
  - Version-specific upgrade steps: upgrade/version-specific.md
- Troubleshooting: troubleshooting.md
- Customization:
  #- Basic customization: customize/index.md
  - Extensions: customize/extensions.md
  #- Other languages: customize/i18n.md
  - Override settings: customize/settings.md
  #- Custom development: customize/develop.md
- CMS Integration:
  - Drupal integration:
    - Drupal Users, Roles and Groups integration: integration/drupal/index.md
    - Drupal views: integration/drupal/views.md
    - Webform: integration/drupal/webform.md
    - WYSIWYG integration: integration/drupal/wysiwyg.md
    - Bootstrap CSS: integration/drupal/bootstrap-css.md
    - Mailhandler: integration/drupal/mailhandler.md
    - Incompatible modules: integration/drupal/incompatibilities.md
  - Backdrop integration:
    - Backdrop Users, Roles and Groups integration: integration/backdrop/index.md
    - Backdrop Views: integration/backdrop/views.md
    - Webform: integration/backdrop/webform.md
  - WordPress integration:
    - WordPress integration: integration/wordpress/index.md
    - Forms in WordPress: integration/wordpress/forms.md
    - Plugin Integration: integration/wordpress/plugins.md
    - Incompatible plugins: integration/wordpress/incompatibilities.md
  - Joomla integration:
    - Joomla integration: integration/joomla/index.md
    - Dashboard in Joomla: integration/joomla/dashboard.md
    - Forms in Joomla: integration/joomla/forms.md
- Special situations:
  - Staging and production: misc/staging-production.md
  #- Switching installation directories: misc/directories.md
  #- Switching domain names: misc/domain-names.md
  - Switching servers: misc/switch-servers.md
  - Switching CMS platforms: misc/switch-cms.md
  #- Data redaction: misc/redaction.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences:
      css_class: codehilite
  - pymdownx.inlinehilite:
      css_class: codehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
